<#
.SYNOPSIS
    Installs yt-dlp into the staged FUNG Whisper runtime so that URL ingest
    (`media_fetch`) can run, and optionally the JavaScript runtime YouTube
    needs for its signature challenges.

.DESCRIPTION
    URL ingest is opt-in and off by default, for one reason and one reason
    only: FUNG's claim is that a meeting stays on the machine that recorded
    it, and this is the one worker in the tree that is *meant* to reach the
    network. Everything else runs with HF_HUB_OFFLINE=1 so that a fetch cannot
    happen by accident. Shipping the fetcher in the default bundle would make
    the capability present on every install whether or not its owner ever
    wanted it, so it is staged deliberately, by hand, once.

    Packages land in `.venv-whisper/Lib/media-fetch-packages`, NOT in the
    runtime's own `site-packages`. That separation is deliberate too:

      * `certifi` and `idna` are pinned by BOTH this set and
        `whisper-runtime-requirements.txt`. Installing over the top would
        silently change the transcription runtime that
        `stage_whisper_runtime.ps1` hashed into its `manifest.json` — the one
        pass the product's local-first promise rests on.
      * Only `fetch_media.py` gets this directory on its PYTHONPATH, so the
        transcription worker cannot import an HTTP client even by mistake.

    The directory sits inside `.venv-whisper` so that the existing
    `bundle.resources` mapping carries it, and so `media_fetch::probe` can
    find it from the same root resolution the interpreter already uses.

.PARAMETER GenerateLock
    Re-resolve the dependency tree with pip and rewrite the hash-pinned
    lockfiles, then stop without installing. Wheel digests are only obtainable
    by downloading the wheels, so this runs on a machine with network access
    and its output is reviewed and committed like any other dependency change.

.PARAMETER WithJsRuntime
    Also install `deno`, which yt-dlp uses to solve YouTube's signature
    challenges through `yt-dlp-ejs`.

    This is separate because it is a 41 MB binary for one site's anti-bot
    measures. Without it, yt-dlp still fetches from most extractors, and
    YouTube specifically will fail on any video whose player requires the
    challenge — which is most of them, most of the time. `media_fetch::probe`
    reports its absence rather than letting the user discover it as a
    download error.

.EXAMPLE
    # On a machine with network access, after stage_whisper_runtime.ps1:
    ./scripts/stage_media_fetch_runtime.ps1 -WithJsRuntime
#>
[CmdletBinding()]
param(
    [string]$YtDlpVersion = '2026.7.4',
    [string]$DenoVersion = '2.8.3',
    [switch]$GenerateLock,
    [switch]$WithJsRuntime
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$venv = Join-Path $repoRoot '.venv-whisper'
$python = Join-Path $venv 'Scripts\python.exe'
$target = Join-Path $venv 'Lib\media-fetch-packages'
$lockfile = Join-Path $PSScriptRoot 'media-fetch-requirements.txt'
$jsLockfile = Join-Path $PSScriptRoot 'media-fetch-js-requirements.txt'
$licensesDir = Join-Path $venv 'LICENSES'

if (-not (Test-Path -LiteralPath $python -PathType Leaf)) {
    throw "No staged FUNG runtime at $venv. Run scripts/stage_whisper_runtime.ps1 first."
}

if ($GenerateLock) {
    # Resolved for the staged interpreter, not the host one: the runtime is
    # CPython 3.11 on win_amd64 regardless of what pip happens to be running
    # under, and `websockets`/`brotli`/`pycryptodomex` all ship per-ABI
    # wheels that would otherwise be pinned for the wrong Python.
    $targets = @(
        @{ Spec = "yt-dlp[default]==$YtDlpVersion"; Lock = $lockfile; Work = 'media-fetch-lock'; NoDeps = $false
           Header = @(
               "# Generated by scripts/stage_media_fetch_runtime.ps1 -GenerateLock"
               "# yt-dlp[default] == $YtDlpVersion, resolved for CPython 3.11 / win_amd64"
               "# Review this file like any other dependency change before committing."
           ) }
        @{ Spec = "deno==$DenoVersion"; Lock = $jsLockfile; Work = 'media-fetch-js-lock'; NoDeps = $true
           Header = @(
               "# Generated by scripts/stage_media_fetch_runtime.ps1 -GenerateLock"
               "# Optional JS runtime for YouTube signature challenges (deno), win_amd64."
               "# Review this file like any other dependency change before committing."
           ) }
    )

    foreach ($entry in $targets) {
        $work = Join-Path $repoRoot ".runtime-cache\$($entry.Work)"
        if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }
        New-Item -ItemType Directory -Path $work -Force | Out-Null

        Write-Host "Resolving $($entry.Spec) ..."
        $pipArgs = @(
            '-m', 'pip', 'download', '--disable-pip-version-check', '--only-binary=:all:',
            '--python-version', '3.11', '--platform', 'win_amd64', '--dest', $work
        )
        if ($entry.NoDeps) { $pipArgs += '--no-deps' }
        & $python @pipArgs $entry.Spec
        if ($LASTEXITCODE -ne 0) { throw "Dependency resolution failed with exit code $LASTEXITCODE" }

        $lines = @($entry.Header)
        Get-ChildItem -LiteralPath $work -File -Filter '*.whl' | Sort-Object Name | ForEach-Object {
            # Wheel filenames are `{name}-{version}-{tags}.whl`; the first two
            # fields are the requirement, the rest is platform tagging.
            $fields = $_.BaseName -split '-'
            if ($fields.Count -lt 2) { throw "Unexpected wheel name: $($_.Name)" }
            $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant()
            $lines += "$($fields[0])==$($fields[1]) --hash=sha256:$hash"
        }
        $lines | Set-Content -LiteralPath $entry.Lock -Encoding utf8
        Write-Host "Wrote $($entry.Lock) ($($lines.Count - $entry.Header.Count) pinned wheels)."
    }
    Write-Host 'Review and commit the lockfiles, then re-run without -GenerateLock.'
    exit 0
}

foreach ($required in @($lockfile, $jsLockfile)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "No pinned lockfile at $required. Run this script with -GenerateLock on a machine with network access, review the result, and commit it."
    }
}

New-Item -ItemType Directory -Path $target -Force | Out-Null

Write-Host "Installing yt-dlp from $lockfile ..."
& $python -m pip install --disable-pip-version-check --no-deps --only-binary=:all: `
    --require-hashes --target $target -r $lockfile
if ($LASTEXITCODE -ne 0) { throw "yt-dlp install failed with exit code $LASTEXITCODE" }

if ($WithJsRuntime) {
    Write-Host "Installing the deno JS runtime from $jsLockfile ..."
    & $python -m pip install --disable-pip-version-check --no-deps --only-binary=:all: `
        --require-hashes --target $target -r $jsLockfile
    if ($LASTEXITCODE -ne 0) { throw "JS runtime install failed with exit code $LASTEXITCODE" }
}

New-Item -ItemType Directory -Path $licensesDir -Force | Out-Null
$licenseSources = [ordered]@{
    'YT-DLP-LICENSE.txt' = "https://raw.githubusercontent.com/yt-dlp/yt-dlp/$YtDlpVersion/LICENSE"
}
if ($WithJsRuntime) {
    $licenseSources['DENO-LICENSE.txt'] = "https://raw.githubusercontent.com/denoland/deno/v$DenoVersion/LICENSE.md"
}
foreach ($entry in $licenseSources.GetEnumerator()) {
    Invoke-WebRequest -Uri $entry.Value -OutFile (Join-Path $licensesDir $entry.Key)
}

# Import rather than assume: "the directory exists" and "the package loads"
# are different claims, and staging is the one place that can afford the
# stronger one. The probe the app runs on every panel open cannot.
$env:PYTHONPATH = $target
$probe = & $python -c "import yt_dlp; print('media-fetch-ready', yt_dlp.version.__version__)"
if ($LASTEXITCODE -ne 0 -or -not ($probe -match 'media-fetch-ready')) {
    throw 'yt-dlp installed but does not import.'
}
Write-Host $probe

if (-not $WithJsRuntime) {
    Write-Host ''
    Write-Host 'JS runtime NOT installed. YouTube will fail on any video whose player'
    Write-Host 'requires a signature challenge. Re-run with -WithJsRuntime to add deno (41 MB).'
}

Write-Host "Staged URL ingest runtime at $target"
Write-Host 'It stays refused until consent is granted: media_fetch_consent_set(enabled: true).'
