<#
.SYNOPSIS
    Installs the speaker-diarization dependencies into the staged FUNG Whisper
    runtime, and optionally warms the gated model cache.

.DESCRIPTION
    Diarization is deliberately NOT part of the default bundle, for two
    reasons that are worth stating rather than discovering:

      1. Size. `pyannote.audio` pulls `torch`, `torchaudio`, `lightning`, and
         their transitive tree. That is hundreds of megabytes on CPU and
         several gigabytes with CUDA wheels — multiples of the entire rest of
         the FUNG installer, imposed on every user for a feature most will
         not use.

      2. Licence. `pyannote/speaker-diarization-3.1` is gated on Hugging
         Face. Each user must accept its terms under their own account, and
         weights obtained that way may not be redistributed inside an
         installer. This is a licence constraint, not an oversight, and it is
         why the Whisper model ships pinned in `stage_whisper_runtime.ps1`
         while this one does not.

    So this script is opt-in, run once, on top of an already-staged runtime.

.PARAMETER GenerateLock
    Resolve the dependency tree with pip and write a hash-pinned lockfile to
    `scripts/diarization-runtime-requirements.txt`, then stop without
    installing.

    This step exists because the pinned set CANNOT be hand-written. Unlike the
    Whisper requirements, whose two dozen entries were resolved once and
    reviewed, the pyannote tree is large, platform-dependent, and changes with
    the torch build selected. Its wheel digests can only be obtained by
    downloading the wheels — so the lockfile is generated on a machine with
    network access, reviewed, and committed, exactly like any other
    dependency change.

.PARAMETER FetchModel
    After installing, download the gated pipeline into FUNG's own Hugging Face
    cache so later runs are offline. Requires FUNG_HF_TOKEN or HF_TOKEN, and
    requires that you have already accepted the licences for BOTH:
        https://huggingface.co/pyannote/speaker-diarization-3.1
        https://huggingface.co/pyannote/segmentation-3.0
    (the 3.1 pipeline loads segmentation-3.0 as a component).

.PARAMETER CacheRoot
    Where to place the model cache. Defaults to the same location the running
    app uses, so a model fetched here is the one the app finds. Override only
    if you also set FUNG_HF_HOME for the app.

.EXAMPLE
    # One-time, on a machine with network access:
    ./scripts/stage_diarization_runtime.ps1 -GenerateLock
    # review + commit scripts/diarization-runtime-requirements.txt, then:
    ./scripts/stage_diarization_runtime.ps1 -FetchModel
#>
[CmdletBinding()]
param(
    [string]$PyannoteVersion = '3.4.0',
    [ValidateSet('cpu', 'cu121')]
    [string]$TorchVariant = 'cpu',
    [string]$CacheRoot,
    [switch]$GenerateLock,
    [switch]$FetchModel
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$venv = Join-Path $repoRoot '.venv-whisper'
$python = Join-Path $venv 'Scripts\python.exe'
$sitePackages = Join-Path $venv 'Lib\site-packages'
$lockfile = Join-Path $PSScriptRoot 'diarization-runtime-requirements.txt'
$licensesDir = Join-Path $venv 'LICENSES'
$model = 'pyannote/speaker-diarization-3.1'

if (-not (Test-Path -LiteralPath $python -PathType Leaf)) {
    throw "No staged FUNG runtime at $venv. Run scripts/stage_whisper_runtime.ps1 first."
}

# The CPU wheels come from PyPI; the CUDA ones only from PyTorch's own index.
# Naming the index explicitly keeps the choice visible in the generated
# lockfile rather than depending on whatever the operator's pip.conf says.
$indexArgs = @()
if ($TorchVariant -ne 'cpu') {
    $indexArgs = @('--extra-index-url', "https://download.pytorch.org/whl/$TorchVariant")
}

if ($GenerateLock) {
    $work = Join-Path $repoRoot ".runtime-cache\diarization-lock"
    New-Item -ItemType Directory -Path $work -Force | Out-Null
    Write-Host "Resolving pyannote.audio==$PyannoteVersion ($TorchVariant) ..."

    # `pip download` resolves the full transitive tree and gives us real
    # wheels to hash. Nothing is installed yet: the point is to produce a
    # reviewable artifact, not to mutate the runtime.
    & $python -m pip download --disable-pip-version-check --only-binary=:all: `
        --dest $work @indexArgs "pyannote.audio==$PyannoteVersion"
    if ($LASTEXITCODE -ne 0) { throw "Dependency resolution failed with exit code $LASTEXITCODE" }

    $lines = @(
        "# Generated by scripts/stage_diarization_runtime.ps1 -GenerateLock"
        "# torch variant: $TorchVariant   pyannote.audio: $PyannoteVersion"
        "# Review this file like any other dependency change before committing."
    )
    Get-ChildItem -LiteralPath $work -File | Sort-Object Name | ForEach-Object {
        # Wheel filenames are `{name}-{version}-{tags}.whl`; the first two
        # fields are the requirement, the rest is platform tagging.
        $fields = $_.BaseName -split '-'
        if ($fields.Count -lt 2) { throw "Unexpected wheel name: $($_.Name)" }
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant()
        $lines += "$($fields[0])==$($fields[1]) --hash=sha256:$hash"
    }
    $lines | Set-Content -LiteralPath $lockfile -Encoding utf8
    Write-Host "Wrote $lockfile ($($lines.Count - 3) pinned wheels)."
    Write-Host 'Review and commit it, then re-run this script without -GenerateLock.'
    exit 0
}

if (-not (Test-Path -LiteralPath $lockfile -PathType Leaf)) {
    throw @"
No pinned lockfile at $lockfile.

The diarization dependency tree cannot be hand-written: its wheel digests are
only obtainable by downloading the wheels. Run this script with -GenerateLock
on a machine with network access, review the result, and commit it.
"@
}

Write-Host "Installing diarization dependencies from $lockfile ..."
& $python -m pip install --disable-pip-version-check --no-deps --only-binary=:all: `
    --require-hashes --target $sitePackages -r $lockfile
if ($LASTEXITCODE -ne 0) { throw "Diarization dependency install failed with exit code $LASTEXITCODE" }

New-Item -ItemType Directory -Path $licensesDir -Force | Out-Null
$licenseSources = [ordered]@{
    'PYANNOTE-AUDIO-LICENSE.txt' = 'https://raw.githubusercontent.com/pyannote/pyannote-audio/develop/LICENSE'
    'PYTORCH-LICENSE.txt'        = 'https://raw.githubusercontent.com/pytorch/pytorch/main/LICENSE'
}
foreach ($entry in $licenseSources.GetEnumerator()) {
    Invoke-WebRequest -Uri $entry.Value -OutFile (Join-Path $licensesDir $entry.Key)
}

# Import rather than assume: the whole point of the readiness probe is that
# "the directory exists" and "the package loads" are different claims, and
# staging is the one place that can afford to check the stronger one.
$probe = & $python -c "import torch, pyannote.audio; print('diarization-deps-ready')"
if ($LASTEXITCODE -ne 0 -or $probe -notcontains 'diarization-deps-ready') {
    throw 'Diarization dependencies installed but do not import.'
}
Write-Host 'Diarization dependencies staged.'

if (-not $FetchModel) {
    Write-Host ''
    Write-Host 'Model not fetched. Re-run with -FetchModel once you have:'
    Write-Host "  1. accepted https://huggingface.co/$model"
    Write-Host '  2. accepted https://huggingface.co/pyannote/segmentation-3.0'
    Write-Host '  3. set FUNG_HF_TOKEN (or HF_TOKEN)'
    exit 0
}

$token = $env:FUNG_HF_TOKEN
if (-not $token) { $token = $env:HF_TOKEN }
if (-not $token) {
    throw 'FUNG_HF_TOKEN (or HF_TOKEN) is required to fetch the gated model.'
}

if (-not $CacheRoot) {
    # Mirrors `diarization::hf_home`: the app looks here, so staging must too,
    # or the download lands somewhere the probe will never find.
    if ($env:FUNG_HF_HOME) {
        $CacheRoot = $env:FUNG_HF_HOME
    } else {
        $CacheRoot = Join-Path $env:APPDATA 'com.fung.desktop\huggingface'
    }
}
New-Item -ItemType Directory -Path $CacheRoot -Force | Out-Null
Write-Host "Fetching $model into $CacheRoot ..."

$env:HF_HOME = $CacheRoot
$fetch = @"
from pyannote.audio import Pipeline
Pipeline.from_pretrained('$model', use_auth_token='$token')
print('diarization-model-ready')
"@
$fetchOutput = & $python -c $fetch
if ($LASTEXITCODE -ne 0 -or $fetchOutput -notcontains 'diarization-model-ready') {
    throw "Model fetch failed. Confirm both licences are accepted for this account."
}
Write-Host "Staged diarization model at $CacheRoot"
